### ISSUE TITLE
Mined Coined List

### ISSUE THREAD

**Issue by JosephRedfern** [bloocoin/bloocoin-client#5]
Bloocoin servers should provide a list of mined coins, including their strings and SHA512sums.

At the moment, there is nothing to stop a server operator from giving themselves and extra 0 on their account balance. By making public the list of mined coins and whose account they are in, we can verify that there's nothing funny going on with account balances.

Until there is a way of proving that users have done work in Bloocoin, it cannot be fully trusted. 

Edit: moved to bloocoin-server: https://github.com/bloocoin/bloocoin-server/issues/9

**Comment by HenryHoggard** [comment]
This is essential in turning this into a currency that people would accept.

**Comment by JosephRedfern** [comment]
People might complain that this will mean that hashes can be redeemed on other servers. This is a problem - but even without this list, it is still and issue. This issue: https://github.com/bloocoin/bloocoin-server/issues/8 might help resolve that problem.

**Comment by JosephRedfern** [comment]
I've moved this issue to bloocoin-server: https://github.com/bloocoin/bloocoin-server/issues/9

**Comment by f-prime** [comment]
This is a great idea which I definitely plan to add. I would love to talk to you on IRC. Could you join irc.rizon.net #blc?

You have some great ideas.

**Comment by JosephRedfern** [comment]
I'm on there as j03 :+1:

**Comment by f-prime** [comment]
Oh, haha, when I get on message me. We need to talk.

**Comment by Jire** [comment]
Creating such a list is equivalent of creating a table filled with spat-out values. Such values are probably online anywhere, and can make BLC mining instantaneous in future efforts.

**Comment by HenryHoggard** [comment]
@Jire There is no reason that @Max00355 is going to reset the difficulty and reset all the coins, so people being able to resubmit them again is not a problem. Besides people already have lists of the coins they have mined, so should he reset the coins, they can just repost their list again, that would be instantaneous.

**Comment by f-prime** [comment]
Who told you I was resetting the coins?

**Comment by HenryHoggard** [comment]
@Max00355 Then use 1s rather than 0s, why are you resetting the coins?
